//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.14.5.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using Shared.Models;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"

namespace DataHub.AnalyticDataStore.Holding.CustomerLoanDelinquency30Days
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.14.5.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface ICustomerLoanDelinquency30DayService
    {
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>Retrieves Loan accounts/contracts details with customer information for loans delinquent for more than 30 days for a specific business date or for the current date</summary>
        /// <param name="businessDate">Business snapshot date of the source data</param>
        /// <param name="useCurrentDate">Current Date flag for the Business date</param>
        /// <param name="delinquentDays">Number of Days a loan is delinquent</param>
        /// <returns>Customer Loan delinquencyResponse</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<GetCustomerLoanDelinquency30DaysResponse> GetCustomerLoanDelinquency30DaysAsync(string? businessDate = null, string? useCurrentDate = null, string? delinquentDays = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    
    }

    /// <summary>getCustomerLoanDelinquency30DaysResponse</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetCustomerLoanDelinquency30DaysResponse 
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public GetCustomerLoanDelinquency30DaysResponseBody? Data { get; set; }= default!;
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class GetCustomerLoanDelinquency30DaysResponseBody 
    {
        [System.Text.Json.Serialization.JsonPropertyName("lendingCustomerAccountDetails")]
        public System.Collections.Generic.ICollection<LendingCustomerAccountDetails>? LendingCustomerAccountDetails { get; set; }= default!;
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.5.2.0 (Newtonsoft.Json v13.0.0.0)")]
    public partial class LendingCustomerAccountDetails 
    {
        /// <summary>Indicates if account is commercial; retail or other</summary>
        [System.Text.Json.Serialization.JsonPropertyName("accountClass")]
        public string? AccountClass { get; set; }= default!;
    
        /// <summary>The affluent bucket of total balance to identify customer segment</summary>
        [System.Text.Json.Serialization.JsonPropertyName("affluentSegment")]
        public string? AffluentSegment { get; set; }= default!;
    
        /// <summary>Age Group</summary>
        [System.Text.Json.Serialization.JsonPropertyName("ageGroup")]
        public string? AgeGroup { get; set; }= default!;
    
        /// <summary>The amortization maturity date.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("amortizationMatureDate")]
        public string? AmortizationMatureDate { get; set; }= default!;
    
        /// <summary>Authorized amount (approved credit limit of the loan; mortgage or LOC)</summary>
        [System.Text.Json.Serialization.JsonPropertyName("authorizedAmount")]
        public string? AuthorizedAmount { get; set; }= default!;
    
        /// <summary>Authorized amount in local currency (approved credit limit of the loan; mortgage or LOC)</summary>
        [System.Text.Json.Serialization.JsonPropertyName("lcyAuthorizedAmount")]
        public string? LcyAuthorizedAmount { get; set; }= default!;
    
        /// <summary>Current balance of the account in reporting currency.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("balance")]
        public string? Balance { get; set; }= default!;
    
        /// <summary>Groups based on balance</summary>
        [System.Text.Json.Serialization.JsonPropertyName("balanceGroup")]
        public string? BalanceGroup { get; set; }= default!;
    
        /// <summary>Current balance in local currency of the contract</summary>
        [System.Text.Json.Serialization.JsonPropertyName("lcyBalance")]
        public string? LcyBalance { get; set; }= default!;
    
        /// <summary>The name of the broker for the contract if applicable</summary>
        [System.Text.Json.Serialization.JsonPropertyName("brokerName")]
        public string? BrokerName { get; set; }= default!;
    
        /// <summary>Business snapshot date of the source data</summary>
        [System.Text.Json.Serialization.JsonPropertyName("businessDate")]
        public string? BusinessDate { get; set; }= default!;
    
        /// <summary>Date the contract was closed</summary>
        [System.Text.Json.Serialization.JsonPropertyName("closedDate")]
        public string? ClosedDate { get; set; }= default!;
    
        /// <summary>Identifier field with no business meaning - Foreign key linking to Contract to Branch</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractBranchKey")]
        public string? ContractBranchKey { get; set; }= default!;
    
        /// <summary>Branch name where Contract was created</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractBranchName")]
        public string? ContractBranchName { get; set; }= default!;
    
        /// <summary>Branch Number</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractBranchNumber")]
        public string? ContractBranchNumber { get; set; }= default!;
    
        /// <summary>Grouping for delinquency days: 'N/A', '1-29 days', '30-89 days', '90-179 days', '180-364 days', '365-999 days', '1000+ days'</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractDelinquencyDayGroup")]
        public string? ContractDelinquencyDayGroup { get; set; }= default!;
    
        /// <summary>Full name of the employee associated with the Contract</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractEmployeeFullName")]
        public string? ContractEmployeeFullName { get; set; }= default!;
    
        /// <summary>Identifier field with no business meaning - Foreign key linking to Contract to Employee</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractEmployeeKey")]
        public string? ContractEmployeeKey { get; set; }= default!;
    
        /// <summary>Employee number of the employee associated with the Contract</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractEmployeeNumber")]
        public string? ContractEmployeeNumber { get; set; }= default!;
    
        /// <summary>Contract number of specific savings; chequing; term deposit; loan, letter of credit, etc.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractNumber")]
        public string? ContractNumber { get; set; }= default!;
    
        /// <summary>Region of the branch associated with the Contract</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractRegion")]
        public string? ContractRegion { get; set; }= default!;
    
        /// <summary>The status of the Contract. i.e Active, Closed, Dormant, Inactive etc</summary>
        [System.Text.Json.Serialization.JsonPropertyName("contractStatus")]
        public string? ContractStatus { get; set; }= default!;
    
        /// <summary>The currency type for the contract.  Typically the standard ISO 3 character country code such as CAD; USD; EUR.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("currency")]
        public string? Currency { get; set; }= default!;
    
        /// <summary>Current Date flag for the Business date</summary>
        [System.Text.Json.Serialization.JsonPropertyName("useCurrentDate")]
        public string? UseCurrentDate { get; set; }= default!;
    
        /// <summary>A Yes/No flag indicating if the customer has been closed within a month of the business date</summary>
        [System.Text.Json.Serialization.JsonPropertyName("customerClosedThisMonth")]
        public string? CustomerClosedThisMonth { get; set; }= default!;
    
        /// <summary>A Yes/No flag indication if the customer has been opened within a month of the business date</summary>
        [System.Text.Json.Serialization.JsonPropertyName("customerNewThisMonth")]
        public string? CustomerNewThisMonth { get; set; }= default!;
    
        /// <summary>The classification for the member either retail or commercial</summary>
        [System.Text.Json.Serialization.JsonPropertyName("customerClass")]
        public string? CustomerClass { get; set; }= default!;
    
        /// <summary>The customer number or customer identification number</summary>
        [System.Text.Json.Serialization.JsonPropertyName("customerNumber")]
        public string? CustomerNumber { get; set; }= default!;
    
        /// <summary>Date Customer started with�the FI�(customer opened date)</summary>
        [System.Text.Json.Serialization.JsonPropertyName("customerStartDate")]
        public string? CustomerStartDate { get; set; }= default!;
    
        /// <summary>The amount that is past due on the loan contract. Immediate payment of this amount is required to put the loan in good standing</summary>
        [System.Text.Json.Serialization.JsonPropertyName("delinquentAmount")]
        public string? DelinquentAmount { get; set; }= default!;
    
        /// <summary>The amount in local currency that is past due on the loan contract. Immediate payment of this amount is required to put the loan in good standing</summary>
        [System.Text.Json.Serialization.JsonPropertyName("delinquentAmountLcy")]
        public string? DelinquentAmountLcy { get; set; }= default!;
    
        /// <summary>Number of Days a loan is delinquent</summary>
        [System.Text.Json.Serialization.JsonPropertyName("delinquentDays")]
        public string? DelinquentDays { get; set; }= default!;
    
        /// <summary>Grouping for delinquency days: 'N/A', '1-29 days', '30-89 days', '90-179 days', '180-364 days', '365-999 days', '1000+ days'</summary>
        [System.Text.Json.Serialization.JsonPropertyName("delinquencyDayGroup")]
        public string? DelinquencyDayGroup { get; set; }= default!;
    
        /// <summary>The date that loan has been disbursed/funded. If more than 1 disbursal; this will be the last disbursal date</summary>
        [System.Text.Json.Serialization.JsonPropertyName("disburseDate")]
        public string? DisburseDate { get; set; }= default!;
    
        /// <summary>Drawdown Account</summary>
        [System.Text.Json.Serialization.JsonPropertyName("drawdownAccount")]
        public string? DrawdownAccount { get; set; }= default!;
    
        /// <summary>The external risk rating code for the account.  This is typically used for reporting to external regulators.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("extenalRiskCode")]
        public string? ExtenalRiskCode { get; set; }= default!;
    
        /// <summary>The description for the external risk rating code</summary>
        [System.Text.Json.Serialization.JsonPropertyName("externalRiskDescription")]
        public string? ExternalRiskDescription { get; set; }= default!;
    
        /// <summary>Indicates if contract interest rate is fixed or variable</summary>
        [System.Text.Json.Serialization.JsonPropertyName("fixedOrVariable")]
        public string? FixedOrVariable { get; set; }= default!;
    
        /// <summary>Customer's gender</summary>
        [System.Text.Json.Serialization.JsonPropertyName("gender")]
        public string? Gender { get; set; }= default!;
    
        /// <summary>The generation gap to identify the suitable product for the group of customers</summary>
        [System.Text.Json.Serialization.JsonPropertyName("generation")]
        public string? Generation { get; set; }= default!;
    
        /// <summary>Contract interest; not paid</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestAccrued")]
        public string? InterestAccrued { get; set; }= default!;
    
        /// <summary>Contract interest in local currency; not paid</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestAccruedLcy")]
        public string? InterestAccruedLcy { get; set; }= default!;
    
        /// <summary>Interest paid  frequency. Determines when interest is paid to the contract. Entry provides information indicating appropriate frequency.   Ex: Monthend; SemiAnn</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestPaidFreq")]
        public string? InterestPaidFreq { get; set; }= default!;
    
        /// <summary>The interest rate for the contract</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestRate")]
        public string? InterestRate { get; set; }= default!;
    
        /// <summary>Groups based on account�interest rate�- '0' -.50%; .50 - 1.00%; 1% - 3% etc.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestRateGroup")]
        public string? InterestRateGroup { get; set; }= default!;
    
        /// <summary>Interest rate index Ex:Prime + 1.00. Usually configured on the banking system at the product level; defines the rate.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestRateIndex")]
        public string? InterestRateIndex { get; set; }= default!;
    
        /// <summary>Interest Rate Type.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestRateType")]
        public string? InterestRateType { get; set; }= default!;
    
        /// <summary>Interest Rate Type Description - LD loans and deps.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestRateTypeDescription")]
        public string? InterestRateTypeDescription { get; set; }= default!;
    
        /// <summary>The contract interest rate variance. Eg. Prime -.50. -.50 is the variance.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestRateVariance")]
        public string? InterestRateVariance { get; set; }= default!;
    
        /// <summary>BL Bill Interpolate</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interpolate")]
        public string? Interpolate { get; set; }= default!;
    
        /// <summary>Daily interest for an contract on the business date; based on the balance and the rate. Negative if it's a demand contract; positive if it's a loan contract.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestIncomeOrExpense")]
        public string? InterestIncomeOrExpense { get; set; }= default!;
    
        /// <summary>Daily interest in local currency for an contract on the business date; based on the balance and the rate. Negative if it's a demand contract; positive if it's a loan contract.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("interestIncomeOrExpenseLcy")]
        public string? InterestIncomeOrExpenseLcy { get; set; }= default!;
    
        /// <summary>Yes/No flag indicating if the account was closed less than a month before the business date</summary>
        [System.Text.Json.Serialization.JsonPropertyName("isClosedThisMonth")]
        public string? IsClosedThisMonth { get; set; }= default!;
    
        /// <summary>Yes/No flag indicating if the account was closed on the business date</summary>
        [System.Text.Json.Serialization.JsonPropertyName("isClosedToday")]
        public string? IsClosedToday { get; set; }= default!;
    
        /// <summary>A Yes/No flag indicating if the account has been opened less than one month before the business date</summary>
        [System.Text.Json.Serialization.JsonPropertyName("isNewThisMonth")]
        public string? IsNewThisMonth { get; set; }= default!;
    
        /// <summary>A Yes/No flag indicating if the account has been opened on the business date</summary>
        [System.Text.Json.Serialization.JsonPropertyName("isNewToday")]
        public string? IsNewToday { get; set; }= default!;
    
        /// <summary>Indicates if the customer is small/medium/enterprise corporate (yes/no))</summary>
        [System.Text.Json.Serialization.JsonPropertyName("isSME")]
        public string? IsSME { get; set; }= default!;
    
        /// <summary>BL BILL Liquidation Mode</summary>
        [System.Text.Json.Serialization.JsonPropertyName("liquidationMode")]
        public string? LiquidationMode { get; set; }= default!;
    
        /// <summary>A user defined code used to classify loans into specific descriptive categories for analysis</summary>
        [System.Text.Json.Serialization.JsonPropertyName("loanCode")]
        public string? LoanCode { get; set; }= default!;
    
        /// <summary>The text description of the loan code</summary>
        [System.Text.Json.Serialization.JsonPropertyName("loanDescription")]
        public string? LoanDescription { get; set; }= default!;
    
        /// <summary>Loan To Value</summary>
        [System.Text.Json.Serialization.JsonPropertyName("loanToValue")]
        public string? LoanToValue { get; set; }= default!;
    
        /// <summary>Marital status of the customer such as single; married; divorced; separated</summary>
        [System.Text.Json.Serialization.JsonPropertyName("maritalStatus")]
        public string? MaritalStatus { get; set; }= default!;
    
        /// <summary>Date the loan or term account will mature</summary>
        [System.Text.Json.Serialization.JsonPropertyName("maturityDate")]
        public string? MaturityDate { get; set; }= default!;
    
        /// <summary>The working occupation of the customer.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("occupation")]
        public string? Occupation { get; set; }= default!;
    
        /// <summary>The original start date or open date of the contract for contracts that have been renewed</summary>
        [System.Text.Json.Serialization.JsonPropertyName("originalStartDate")]
        public string? OriginalStartDate { get; set; }= default!;
    
        /// <summary>The amount the account is overdrawn</summary>
        [System.Text.Json.Serialization.JsonPropertyName("overdrawnAmount")]
        public string? OverdrawnAmount { get; set; }= default!;
    
        /// <summary>The amount the account is overdrawn in local currency</summary>
        [System.Text.Json.Serialization.JsonPropertyName("overdrawnAmountLcy")]
        public string? OverdrawnAmountLcy { get; set; }= default!;
    
        /// <summary>The frequency that the payment should be made on the loan contract</summary>
        [System.Text.Json.Serialization.JsonPropertyName("paymentFrequency")]
        public string? PaymentFrequency { get; set; }= default!;
    
        /// <summary>Primary collateral code for the loan account</summary>
        [System.Text.Json.Serialization.JsonPropertyName("primaryCollateralCode")]
        public string? PrimaryCollateralCode { get; set; }= default!;
    
        /// <summary>Primary collateral code for the loan account</summary>
        [System.Text.Json.Serialization.JsonPropertyName("primaryCollateralDescription")]
        public string? PrimaryCollateralDescription { get; set; }= default!;
    
        /// <summary>Grouping of product codes</summary>
        [System.Text.Json.Serialization.JsonPropertyName("productGroupCode")]
        public string? ProductGroupCode { get; set; }= default!;
    
        /// <summary>Description of product groups</summary>
        [System.Text.Json.Serialization.JsonPropertyName("productGroupDescription")]
        public string? ProductGroupDescription { get; set; }= default!;
    
        /// <summary>Grouping of product types</summary>
        [System.Text.Json.Serialization.JsonPropertyName("productGroupType")]
        public string? ProductGroupType { get; set; }= default!;
    
        /// <summary>Line code of the product</summary>
        [System.Text.Json.Serialization.JsonPropertyName("productLineCode")]
        public string? ProductLineCode { get; set; }= default!;
    
        /// <summary>Line description of the product</summary>
        [System.Text.Json.Serialization.JsonPropertyName("productLineDescription")]
        public string? ProductLineDescription { get; set; }= default!;
    
        /// <summary>The code used to identify the type of product the account represents.  This  code is the base for classifying products into  classifications; categories; groups and classes.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("productCode")]
        public string? ProductCode { get; set; }= default!;
    
        /// <summary>The description of the product based on the product code</summary>
        [System.Text.Json.Serialization.JsonPropertyName("productDescription")]
        public string? ProductDescription { get; set; }= default!;
    
        /// <summary>A classification field for product which is typically less granular than product code</summary>
        [System.Text.Json.Serialization.JsonPropertyName("productType")]
        public string? ProductType { get; set; }= default!;
    
        /// <summary>Purpose code (usually a numeric value) on the loan contract; also know as purpose for borrowing.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("purposeCode")]
        public string? PurposeCode { get; set; }= default!;
    
        /// <summary>A text description of the Purpose Code.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("purposeDescription")]
        public string? PurposeDescription { get; set; }= default!;
    
        /// <summary>ReasonClosed</summary>
        [System.Text.Json.Serialization.JsonPropertyName("reasonClosed")]
        public string? ReasonClosed { get; set; }= default!;
    
        /// <summary>contract next review date; usually used for Lines of Credit</summary>
        [System.Text.Json.Serialization.JsonPropertyName("reviewDate")]
        public string? ReviewDate { get; set; }= default!;
    
        /// <summary>Code used to assign risk level to an account - FI defined</summary>
        [System.Text.Json.Serialization.JsonPropertyName("riskCode")]
        public string? RiskCode { get; set; }= default!;
    
        /// <summary>Text description for Risk Rating Code.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("riskDescription")]
        public string? RiskDescription { get; set; }= default!;
    
        /// <summary>Scheduled Payment Amount</summary>
        [System.Text.Json.Serialization.JsonPropertyName("schedulePaymentAmount")]
        public string? SchedulePaymentAmount { get; set; }= default!;
    
        /// <summary>Scheduled Payment Amount in local currency</summary>
        [System.Text.Json.Serialization.JsonPropertyName("schedulePaymentAmountLcy")]
        public string? SchedulePaymentAmountLcy { get; set; }= default!;
    
        /// <summary>The term length of the product calculated in standard months. i.e. 12; 24; 36 ....60.  If the term length is not a standard number; this value is rounded to the nearest standard term. For example a 13 month term is rounded to 12 months.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("standardizedTerm")]
        public string? StandardizedTerm { get; set; }= default!;
    
        /// <summary>Date the contract was opened</summary>
        [System.Text.Json.Serialization.JsonPropertyName("startDate")]
        public string? StartDate { get; set; }= default!;
    
        /// <summary>Text description of the account that is printed on statements. i.e Vacation Account</summary>
        [System.Text.Json.Serialization.JsonPropertyName("statementDescription")]
        public string? StatementDescription { get; set; }= default!;
    
        /// <summary>Term Length (0;1;3;6;9;12;18;24;36;48;60;84) could be months; days; years - see term unit.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("term")]
        public string? Term { get; set; }= default!;
    
        /// <summary>Term length converted to months. Calculated based on term and term Unit</summary>
        [System.Text.Json.Serialization.JsonPropertyName("termInMonths")]
        public string? TermInMonths { get; set; }= default!;
    
        /// <summary>The integer value of the remaining term to the maturity date of the product.</summary>
        [System.Text.Json.Serialization.JsonPropertyName("termToMaturity")]
        public string? TermToMaturity { get; set; }= default!;
    
        /// <summary>The groups or bucketing for term to maturity</summary>
        [System.Text.Json.Serialization.JsonPropertyName("termToMaturityGroup")]
        public string? TermToMaturityGroup { get; set; }= default!;
    
        /// <summary>Unit of term length (days; months; years)</summary>
        [System.Text.Json.Serialization.JsonPropertyName("termUnit")]
        public string? TermUnit { get; set; }= default!;
    
        /// <summary>The sum of all deposit and loan balances</summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalBalance")]
        public string? TotalBalance { get; set; }= default!;
    
        /// <summary>Total Balance Amount in local currency)</summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalBalanceLcy")]
        public string? TotalBalanceLcy { get; set; }= default!;
    
        /// <summary>Amount that is charged for operation by customer</summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalCharges")]
        public string? TotalCharges { get; set; }= default!;
    
        /// <summary>Amount in local currency that is charged for operation by customer</summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalChargesLcy")]
        public string? TotalChargesLcy { get; set; }= default!;
    
        /// <summary>Total Due Amount</summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalDue")]
        public string? TotalDue { get; set; }= default!;
    
        /// <summary>Total Due Amount in local currency</summary>
        [System.Text.Json.Serialization.JsonPropertyName("totalDueLcy")]
        public string? TotalDueLcy { get; set; }= default!;
    
        /// <summary>Unspecified Amount</summary>
        [System.Text.Json.Serialization.JsonPropertyName("unspecifiedAmount")]
        public string? UnspecifiedAmount { get; set; }= default!;
    
        /// <summary>Unspecified Amount in local currency</summary>
        [System.Text.Json.Serialization.JsonPropertyName("unspecifiedAmountLcy")]
        public string? UnspecifiedAmountLcy { get; set; }= default!;
    
    
    }

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016