using Transact.Reference;
using Transact.Reference.AccountOfficers;
using Transact.Reference.BalanceTypes;
using Transact.Reference.Beneficiaries;
using Transact.Reference.BICs;
using Transact.Reference.Brokers;
using Transact.Reference.BundleRates;
using Transact.Reference.Categories;
using Transact.Reference.ChequeTypes;
using Transact.Reference.CollateralClassifications;
using Transact.Reference.Companies;
using Transact.Reference.Countries;
using Transact.Reference.Currencies;
using Transact.Reference.Dates;
using Transact.Reference.Dealers;
using Transact.Reference.IBANs;
using Transact.Reference.InterestBases;
using Transact.Reference.InterestRates;
using Transact.Reference.Lookups;
using Transact.Reference.NationalIds;
using Transact.Reference.OrganizationStructuresServices;
using Transact.Reference.PeriodDates;
using Transact.Reference.PortfolioAccounts;
using Transact.Reference.Product;
using Transact.Reference.RoundingRule;
using Transact.Reference.TransactionCodesServices;
using Transact.Reference.Treasury;
using Transact.Reference.UsBenOwnerTypes;
using Transact.Reference.UsCounty;
using Transact.Reference.UsCovenant;
using Transact.Reference.UsCustomerRating;
using Transact.Reference.UsCustomerSuffix;
using Transact.Reference.UsCustomerTitle;
using Transact.Reference.UsFdicClassCodes;
using Transact.Reference.UsHoldTypes;
using Transact.Reference.UsIdDocuments;
using Transact.Reference.UsIndustry;
using Transact.Reference.UsSector;
using Transact.Reference.UsSortCodesServices;
using Transact.Reference.UsState;

namespace Transact;

public class ReferenceClient : IReferenceClient
{
    private readonly HttpClient _httpClient;
    public string BaseUrl { get; set; } = Shared.Data.DefaultConfig.BaseUrl;
    public bool ReadResponseAsString { get; set; } = Shared.Data.DefaultConfig.ReadResponseAsString;
    public ReferenceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }
    public IAccountOfficersService AccountOfficersService => new AccountOfficersService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IBalanceTypesService BalanceTypesService => new BalanceTypesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IBeneficiariesService BeneficiariesService => new BeneficiariesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IBICsService BICsService => new BICsService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IBrokersService BrokersService => new BrokersService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IBundleRatesService BundleRatesService => new BundleRatesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public ICategoriesService CategoriesService => new CategoriesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IChequeTypesService ChequeTypesService => new ChequeTypesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public ICollateralClassificationsService CollateralClassificationsService => new CollateralClassificationsService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public ICompaniesService CompaniesService => new CompaniesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public ICountriesService CountriesService => new CountriesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public ICurrenciesService CurrenciesService => new CurrenciesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IDatesService DatesService => new DatesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IDealersService DealersService => new DealersService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IIBANsService IBANsService => new IBANsService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IInterestBasesService InterestBasesService => new InterestBasesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IInterestRatesService InterestRatesService => new InterestRatesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public ILookupsService LookupsService => new LookupsService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public INationalIdsService NationalIdsService => new NationalIdsService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IOrganizationStructuresServicesService OrganizationStructuresServicesService => new OrganizationStructuresServicesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IPeriodDatesService PeriodDatesService => new PeriodDatesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IPortfolioAccountsService PortfolioAccountsService => new PortfolioAccountsService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IProductService ProductService => new ProductService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IRoundingRuleService RoundingRuleService => new RoundingRuleService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public ITransactionCodesServicesService TransactionCodesServicesService => new TransactionCodesServicesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public ITreasuryService TreasuryService => new TreasuryService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsBenOwnerTypesService UsBenOwnerTypesService => new UsBenOwnerTypesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsCountyService UsCountyService => new UsCountyService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsCovenantService UsCovenantService => new UsCovenantService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsCustomerRatingService UsCustomerRatingService => new UsCustomerRatingService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsCustomerSuffixService UsCustomerSuffixService => new UsCustomerSuffixService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsCustomerTitleService UsCustomerTitleService => new UsCustomerTitleService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsFdicClassCodesService UsFdicClassCodesService => new UsFdicClassCodesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsHoldTypesService UsHoldTypesService => new UsHoldTypesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsIdDocumentsService UsIdDocumentsService => new UsIdDocumentsService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsIndustryService UsIndustryService => new UsIndustryService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsSectorService UsSectorService => new UsSectorService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsSortCodesServicesService UsSortCodesServicesService => new UsSortCodesServicesService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
    public IUsStateService UsStateService => new UsStateService(_httpClient) { BaseUrl = BaseUrl, ReadResponseAsString = ReadResponseAsString };
}
