using FundAdministration.GlobalAccounting.Holding;
using FundAdministration.GlobalAccounting.Holding.CallDepositTransactions;
using FundAdministration.GlobalAccounting.Holding.CapitalDecreaseByNewSecurity;
using FundAdministration.GlobalAccounting.Holding.CapitalDecreaseCollectionOfShares;
using FundAdministration.GlobalAccounting.Holding.CapitalDecreaseOfParValuesDomesticShare;
using FundAdministration.GlobalAccounting.Holding.CapitalDecreaseOfParValuesForeignShare;
using FundAdministration.GlobalAccounting.Holding.CapitalDecreaseOfParValuesWithRealizedGain;
using FundAdministration.GlobalAccounting.Holding.CapitalIIncreaseWithExerciseOfSubscriptionRights;
using FundAdministration.GlobalAccounting.Holding.CapitalIncreaseWithoutIssueOfSubscriptionRights;
using FundAdministration.GlobalAccounting.Holding.CashDividendAnnouncement;
using FundAdministration.GlobalAccounting.Holding.CiaSubscriptionRight;
using FundAdministration.GlobalAccounting.Holding.CouponDividendTransaction;
using FundAdministration.GlobalAccounting.Holding.DebitCreditTransaction;
using FundAdministration.GlobalAccounting.Holding.EosCashCompensation;
using FundAdministration.GlobalAccounting.Holding.EosMultipleSecurity;
using FundAdministration.GlobalAccounting.Holding.EosNewSecurityWithoutCash;
using FundAdministration.GlobalAccounting.Holding.EosSameSecurity;
using FundAdministration.GlobalAccounting.Holding.Equity;
using FundAdministration.GlobalAccounting.Holding.ExchangeOfNewSecurityWithCashInflow;
using FundAdministration.GlobalAccounting.Holding.ExchangeOfNewSecurityWithCashOutflow;
using FundAdministration.GlobalAccounting.Holding.FixedBond;
using FundAdministration.GlobalAccounting.Holding.FixedMbsIpb;
using FundAdministration.GlobalAccounting.Holding.FloatingVariableBond;
using FundAdministration.GlobalAccounting.Holding.FloatOrRateFactor;
using FundAdministration.GlobalAccounting.Holding.ForwardForeignExchange;
using FundAdministration.GlobalAccounting.Holding.ForwardForeignExchangeRepayment;
using FundAdministration.GlobalAccounting.Holding.FundShareTransaction;
using FundAdministration.GlobalAccounting.Holding.Future;
using FundAdministration.GlobalAccounting.Holding.FutureFee;
using FundAdministration.GlobalAccounting.Holding.FutureMaturity;
using FundAdministration.GlobalAccounting.Holding.FutureTransaction;
using FundAdministration.GlobalAccounting.Holding.FutureTransactionsRebooking;
using FundAdministration.GlobalAccounting.Holding.IrsTransactions;
using FundAdministration.GlobalAccounting.Holding.OptionExercise;
using FundAdministration.GlobalAccounting.Holding.OptionFee;
using FundAdministration.GlobalAccounting.Holding.OptionMaturity;
using FundAdministration.GlobalAccounting.Holding.OptionTransaction;
using FundAdministration.GlobalAccounting.Holding.OptionTransactionsRebooking;
using FundAdministration.GlobalAccounting.Holding.PikBond;
using FundAdministration.GlobalAccounting.Holding.ReverseStockSplit;
using FundAdministration.GlobalAccounting.Holding.SecurityTransactionRebooking;
using FundAdministration.GlobalAccounting.Holding.SpinOff;
using FundAdministration.GlobalAccounting.Holding.SpotForeignExchange;
using FundAdministration.GlobalAccounting.Holding.StockDividend;
using FundAdministration.GlobalAccounting.Holding.StockExchangeTransactionFee;
using FundAdministration.GlobalAccounting.Holding.StockSplit;
using FundAdministration.GlobalAccounting.Holding.TermDepositTransaction;
using FundAdministration.GlobalAccounting.Holding.VariableMbs;
using FundAdministration.GlobalAccounting.Holding.ZeroCoupon;

namespace FundAdministration.GlobalAccounting;

public class HoldingClient : IHoldingClient
{
    private readonly HttpClient _httpClient;
    public string BaseUrl { get; set; } = Shared.Data.DefaultConfig.BaseUrl;

    public HoldingClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }
    public ICallDepositTransactionsService CallDepositTransactionService => new CallDepositTransactionsService(_httpClient) { BaseUrl = BaseUrl };
    public ICapitalDecreaseByNewSecurityService CapitalDecreaseByNewSecurityService => new CapitalDecreaseByNewSecurityService(_httpClient) { BaseUrl = BaseUrl };
    public ICapitalDecreaseCollectionOfSharesService CapitalDecreaseCollectionOfShareService => new CapitalDecreaseCollectionOfSharesService(_httpClient) { BaseUrl = BaseUrl };
    public ICapitalDecreaseOfParValuesDomesticShareService CapitalDecreaseOfParValueDomesticShareService => new CapitalDecreaseOfParValuesDomesticShareService(_httpClient) { BaseUrl = BaseUrl };
    public ICapitalDecreaseOfParValuesForeignShareService CapitalDecreaseOfParValueForeignShareService => new CapitalDecreaseOfParValuesForeignShareService(_httpClient) { BaseUrl = BaseUrl };
    public ICapitalDecreaseOfParValuesWithRealizedGainService CapitalDecreaseOfParValueDomesticSharesTaxablePayment => new CapitalDecreaseOfParValuesWithRealizedGainService(_httpClient) { BaseUrl = BaseUrl };
    public ICapitalIIncreaseWithExerciseOfSubscriptionRightsService CapitalIIncreaseWithExerciseOfSubscriptionRightService => new CapitalIIncreaseWithExerciseOfSubscriptionRightsService(_httpClient) { BaseUrl = BaseUrl };
    public ICapitalIncreaseWithoutIssueOfSubscriptionRightsService CapitalIncreaseWithoutIssueOfSubscriptionRightService => new CapitalIncreaseWithoutIssueOfSubscriptionRightsService(_httpClient) { BaseUrl = BaseUrl };
    public ICashDividendAnnouncementService CashDividendAnnouncementService => new CashDividendAnnouncementService(_httpClient) { BaseUrl = BaseUrl };
    public ICiaSubscriptionRightService CapitalIncreaseAllotmentSubscriptionRightService => new CiaSubscriptionRightService(_httpClient) { BaseUrl = BaseUrl };
    public ICouponDividendTransactionService CouponDividendTransactionService => new CouponDividendTransactionService(_httpClient) { BaseUrl = BaseUrl };
    public IDebitCreditTransactionService DebitCreditTransactionService => new DebitCreditTransactionService(_httpClient) { BaseUrl = BaseUrl };
    public IEosCashCompensationService ExchangeOfSecurityNewSecurityWithCashCompensationService => new EosCashCompensationService(_httpClient) { BaseUrl = BaseUrl };
    public IEosMultipleSecurityService EosMultipleSecurityService => new EosMultipleSecurityService(_httpClient) { BaseUrl = BaseUrl };
    public IEosNewSecurityWithoutCashService ExchangeOfSecurityNewSecurityWithoutCashCompensationService => new EosNewSecurityWithoutCashService(_httpClient) { BaseUrl = BaseUrl };
    public IEosSameSecurityService ExchangeOfSecuritySameSecurityService => new EosSameSecurityService(_httpClient) { BaseUrl = BaseUrl };
    public IEquityService EquityService => new EquityService(_httpClient) { BaseUrl = BaseUrl };
    public IExchangeOfNewSecurityWithCashInflowService ExchangeOfNewSecurityWithCashInflowService => new ExchangeOfNewSecurityWithCashInflowService(_httpClient) { BaseUrl = BaseUrl };
    public IExchangeOfNewSecurityWithCashOutflowService ExchangeOfNewSecurityWithCashOutflowService => new ExchangeOfNewSecurityWithCashOutflowService(_httpClient) { BaseUrl = BaseUrl };
    public IFixedBondService FixedBondService => new FixedBondService(_httpClient) { BaseUrl = BaseUrl };
    public IFixedMbsIpbService FixedMortgageBackedSecurityOrInflationProtectedBondService => new FixedMbsIpbService(_httpClient) { BaseUrl = BaseUrl };
    public IFloatingVariableBondService FloatingVariableRateBondService => new FloatingVariableBondService(_httpClient) { BaseUrl = BaseUrl };
    public IFloatOrRateFactorService FloatingRateOrFactorLoadService => new FloatOrRateFactorService(_httpClient) { BaseUrl = BaseUrl };
    public IForwardForeignExchangeRepaymentService ForwardForeignExchangeRepaymentService => new ForwardForeignExchangeRepaymentService(_httpClient) { BaseUrl = BaseUrl };
    public IForwardForeignExchangeService ForwardForeignExchangeService => new ForwardForeignExchangeService(_httpClient) { BaseUrl = BaseUrl };
    public IFundShareTransactionService ShareholderService => new FundShareTransactionService(_httpClient) { BaseUrl = BaseUrl };
    public IFutureFeeService FutureFeeService => new FutureFeeService(_httpClient) { BaseUrl = BaseUrl };
    public IFutureMaturityService FutureMaturityService => new FutureMaturityService(_httpClient) { BaseUrl = BaseUrl };
    public IFutureService FutureService => new FutureService(_httpClient) { BaseUrl = BaseUrl };
    public IFutureTransactionService FutureTransactionService => new FutureTransactionService(_httpClient) { BaseUrl = BaseUrl };
    public IFutureTransactionsRebookingService FutureTransactionRebookingService => new FutureTransactionsRebookingService(_httpClient) { BaseUrl = BaseUrl };
    public IIrsTransactionsService SwapService => new IrsTransactionsService(_httpClient) { BaseUrl = BaseUrl };
    public IOptionExerciseService OptionExerciseService => new OptionExerciseService(_httpClient) { BaseUrl = BaseUrl };
    public IOptionFeeService OptionFeeService => new OptionFeeService(_httpClient) { BaseUrl = BaseUrl };
    public IOptionMaturityService OptionMaturityService => new OptionMaturityService(_httpClient) { BaseUrl = BaseUrl };
    public IOptionTransactionService OptionTransactionService => new OptionTransactionService(_httpClient) { BaseUrl = BaseUrl };
    public IOptionTransactionsRebookingService OptionTransactionRebookingService => new OptionTransactionsRebookingService(_httpClient) { BaseUrl = BaseUrl };
    public IPikBondService PikBondService => new PikBondService(_httpClient) { BaseUrl = BaseUrl };
    public IReverseStockSplitService ReverseStockSplitService => new ReverseStockSplitService(_httpClient) { BaseUrl = BaseUrl };
    public ISecurityTransactionRebookingService SecurityTransactionRebookingService => new SecurityTransactionRebookingService(_httpClient) { BaseUrl = BaseUrl };
    public ISpinOffService SpinOffService => new SpinOffService(_httpClient) { BaseUrl = BaseUrl };
    public ISpotForeignExchangeService SpotForeignExchangeService => new SpotForeignExchangeService(_httpClient) { BaseUrl = BaseUrl };
    public IStockDividendService StockDividendService => new StockDividendService(_httpClient) { BaseUrl = BaseUrl };
    public IStockExchangeTransactionFeeService StockExchangeFeeService => new StockExchangeTransactionFeeService(_httpClient) { BaseUrl = BaseUrl };
    public IStockSplitService StockSplitService => new StockSplitService(_httpClient) { BaseUrl = BaseUrl };
    public ITermDepositTransactionService TimeTermDepositService => new TermDepositTransactionService(_httpClient) { BaseUrl = BaseUrl };
    public IVariableMbsService VariableMortgageBackedSecurityService => new VariableMbsService(_httpClient) { BaseUrl = BaseUrl };
    public IZeroCouponService ZeroCouponService => new ZeroCouponService(_httpClient) { BaseUrl = BaseUrl };

    public IExchangeOfSecurity ExchangeOfSecurity => new ExchangeOfSecurity(_httpClient) { BaseUrl = BaseUrl };
}
